### PR TITLE
bugfix use new url and format for frozen incidence XSLX

### LINKED ISSUE #393: Frozen Incidence URL hat sich geändert
Hallo,

ich benutze die Frozen incidence der API. Soweit ich das verstehe wird dabei ja eine Excel Datei runter geladen und die einzelnen Sheets dabei auseinander gepflückt und diese Daten werden dann zur Verfügung gestellt.

Mein Aufruf: https://api.corona-zahlen.org/districts/11111/history/frozen-incidence/7
Dabei kommt folgender Fehler:
`
{
error: {
message: "An error occurred.",
details: "Invalid HTML: could not find <table>",
stack: "Error: Invalid HTML: could not find <table>
    at Object.html_to_book [as to_workbook] (/workspace/node_modules/xlsx/xlsx.js:20308:39)
    at parse_xlml_xml (/workspace/node_modules/xlsx/xlsx.js:16530:26)
    at parse_xlml (/workspace/node_modules/xlsx/xlsx.js:17251:53)
    at Object.readSync [as read] (/workspace/node_modules/xlsx/xlsx.js:21888:21)
    at /workspace/src/data-requests/frozen-incidence.ts:30:23
    at Generator.next (<anonymous>)
    at fulfilled (/workspace/dist/data-requests/frozen-incidence.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
}
}
`

Soweit ich sehe, gibt es diese Excel Datei nicht mehr unter der URL wie sie im Quelltext steht:
https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Daten/Fallzahlen_Kum_Tab.xlsx?__blob=publicationFile

Es wurde aufgeteilt in aktuelle Zahlen und archivierte Zahlen:

**Aktuelle Zahlen**
https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Daten/Fallzahlen_Kum_Tab_aktuell.xlsx?__blob=publicationFile

**Archiv Zahlen**
https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Daten/Fallzahlen_Kum_Tab_Archiv.xlsx?__blob=publicationFile

Bitte passt das doch mal an, wenn Zeit ist. 
Ich würde die URL der aktuellen Zahlen für die frozen incidence nehmen.

### PR DESCRIPTION
**Pull request by csigritz**
The XLS file located at https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Daten/Fallzahlen_Kum_Tab.xlsx?\_\_blob=publicationFile is not available anymore.
A file with changes in data format is now available at https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Daten/Fallzahlen_Kum_Tab_aktuell.xlsx?__blob=publicationFile

Documentation of URLs on RKI website: https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Daten/Fallzahlen_Kum_Tab.xlsx?__blob=publicationFile

Fix #393

### CODE REVIEW

**Comment by Rubber1Duck** [comment]
in this way we are loosing the history values bevor 2021-09-11 !
minimum if thies values are request we should open the archiv file too!

**Review by Rubber1Duck — CHANGES_REQUESTED** [review]
in this way we are loosing the history values bevor 2021-09-11 !
minimum if those values are request we should open the archiv file too!

**Comment by csigritz** [comment]
Well. Then probably parsing both files must be implemented.

**Comment by Rubber1Duck** [comment]
> Well. Then probably parsing both files must be implemented.

That sounds great, will you do that?

**Comment by csigritz** [comment]
Yep. Will implement it.

**Comment by csigritz** [comment]
@Rubber1Duck Added parsing archive files if days is more than in active file or days param is not given.

File: src/data-requests/frozen-incidence.ts [hunk 1]
```diff
@@ -49,24 +52,104 @@ export async function getDistrictsFrozenIncidenceHistory(
...
+    fetchArchiveData = districts.length > 0 && districts[0].history.length > 0; // check if we got data already;
+  } else {
+    const reference_date = new Date(getDateBefore(days));
+    if (districts.length > 0 && districts[0].history.length > 0) {
+      // check if we got data already
+      if (districts[0].history.length < days) {
+        fetchArchiveData = true;
+      }
+    }
+  }
```
Comment (Rubber1Duck) [inline src/data-requests/frozen-incidence.ts]: `if (days === null) {` is not working here because wenn days is unset it is undefined and NOT null!
`const reference_date = new Date(getDateBefore(days));` is obsolate here, is defined but never used in this context

may I suggest the following?
`const fetchArchiveData = !days
    ? districts.length > 0 && districts[0].history.length > 0
    : districts.length > 0 &&
      districts[0].history.length > 0 &&
      districts[0].history.length < days;`

File: src/data-requests/frozen-incidence.ts [hunk 2]
```diff
@@ -134,6 +256,50 @@ export async function getStatesFrozenIncidenceHistory(
...
+    fetchArchiveData = states.length > 0 && states[0].history.length > 0; // check if we got data already;
+  } else {
+    const reference_date = new Date(getDateBefore(days));
+    if (states.length > 0 && states[0].history.length > 0) {
+      // check if we got data already
+      if (states[0].history.length < days) {
+        fetchArchiveData = true;
+      }
+    }
+  }
```
Comment (Rubber1Duck) [inline src/data-requests/frozen-incidence.ts]: here the same as for districts

File: src/utils.ts [hunk 3]
```diff
@@ -207,6 +207,20 @@ export function getDayDifference(date1: Date, date2: Date): number {
   return Math.ceil(diffTime / (1000 * 60 * 60 * 24));
 }
 
+export function getDateFromString(dateString: string): Date {
+  if (dateString.indexOf("/") > -1) {
+    // probably this format: 8/25/21: m/d/y
```
Comment (Rubber1Duck) [inline src/utils.ts]: There is no need of string conversion for date string in format m/d/y because `new date(sting in format m/d/y)` will always return a valid date!
So if we want this additional function, but i'm not sure (witch is only used here!) 
```export function getDateFromString(dateString: string): Date {
  if (dateString.indexOf("/") > -1) {
    // probably this format: 8/25/21: m/d/y
    return new Date(dateString);
  } else {
    // probably this format: 01.12.2020: dd.mm.yyyy
    const date_pattern = /(\d{2})\.(\d{2})\.(\d{4})/;
    return new Date(dateString.replace(date_pattern, "$3-$2-$1"));
  }
}```
will do the same job!

**Review by Rubber1Duck — CHANGES_REQUESTED** [review]

**Comment by Rubber1Duck** [comment]
> @Rubber1Duck Added parsing archive files if days is more than in active file or days param is not given.

thanks for the PR, but some changes where needed!

File: src/utils.ts (hunk 3 above)
Comment (csigritz) [reply src/utils.ts]: I tried that before. But it is strange. 

New Date from a m/d/y returns this date:
```js
const dateString = "8/25/21";
console.log(new Date(dateString));   //returns 2021-08-24T22:00:00.000Z
```

But new Date from a yyyy-mm-dd returns this:
```js
const dateString = "2021-08-25";
console.log(new Date(dateString));   //returns 2021-08-25T00:00:00.000Z
```

This led to inconsistent date entries in the history result array. Some entries have been at 22pm. The others not. And that's why I tried to bring the dates into the same source format.

Comment (csigritz) [reply src/utils.ts]: This little js snippet shows the problem:
Bildschirmfoto 2022-02-09 um 20 30 28

Comment (Rubber1Duck) [reply src/utils.ts]: Okay you are right! that is because your computer is running in timerzone GMT +2.
The Dockercontainer is running in GMT and then both dates are the same.
there are serval points the system is reacting in this way!
And i agree that your way is the way with more consistency, so let it as it is. 
But the function is only needed in frozen-incidence.ts so in my opinion it makes more sence to put that funtion in frozen-incidence.ts and not in utils.ts!
Und unfortnatly i found another little bug
to decide if the archive data must be loaded you compare the length of the history with the number of days that are given as the request parameter days. (as one part of the decisiontree)
`districts[0].history.length < days`
per definition the days parameter is from today x days in the past.
Unfortunately the RKI is not providing the frozen-incidence value every day, they update the excelsheet only mondays.
The count of historyentry is different to that day parameter!
the comparement should be
compare the date of the lowest date in the history with the date x days in the past from today!
`districts[0].history[0].date < new Date(getDateBefore(days))`
for both states and districts

Comment (csigritz) [reply src/utils.ts]: Ok. I will change that. But I think that it should be the other way:
`districts[0].history[0].date > new Date(getDateBefore(days))`

Comment (Rubber1Duck) [reply src/utils.ts]: tell me why do you think so?

Comment (csigritz) [reply src/utils.ts]: Well. If the first (so the minimum) date in the current history array is newer than our desired target date, then we should fetch the archive.

Comment (Rubber1Duck) [reply src/utils.ts]: of corse you are rigth. I just debug this and i wonder why the archiv data will be loaded wenn the parameter is 14 days!
there is another bug since a long time!
change also the first days filter 
```
      history = history.filter((element) > element.date > reference_date);
```
in row 241 this is the old bug and 272 also 
to 
```
      history = history.filter((element) => element.date >= reference_date);

```
and for districts also
row 104 and 131
please

Comment (csigritz) [reply src/utils.ts]: But this will give 4 history entries when days is 3. Or is this is also some problem with not running in a Docker Container?
image

Comment (Rubber1Duck) [reply src/utils.ts]: pfffff i have only 2 entrys
2022-02-09 21_12_20-Mozilla Firefox
dammed :-)
Today is the 9th 3 days ago is the 6th so I would actually expect the 6th, 7th and 8th and, if available, the 9th. but the 9th is not in the file. But why am I missing the 6th??

Comment (Rubber1Duck) [reply src/utils.ts]: sorry forget about it
i have 3 entrys
2022-02-09 21_24_30-Mozilla Firefox

Comment (Rubber1Duck) [reply src/utils.ts]: and that is what i expect

Comment (Rubber1Duck) [reply src/utils.ts]: change your timezone to GMT i i would expect that you have the same result

Comment (Rubber1Duck) [reply src/utils.ts]: sorry you cant see the whole address
2022-02-09 21_27_51-Mozilla Firefox

Comment (csigritz) [reply src/utils.ts]: So. I am a bit confused now. Should I change the `>` to `>=`? Or keep it the way it is?

Comment (Rubber1Duck) [reply src/utils.ts]: i am confused too :-)
i think to not change the logic witch dates are shown DONT change `>` to `>=`
but to not alwasy load the archiv data change 
`states[0].history[0].date > new Date(getDateBefore(days));`
to
`states[0].history[0].date > new Date(getDateBefore(days - 1));`

districts also

Comment (csigritz) [reply src/utils.ts]: Done

Comment (Rubber1Duck) [reply src/utils.ts]: Thanks very much

**Review by Rubber1Duck — APPROVED** [review]
